### ISSUE TITLE
Missing NPM Versions

### ISSUE THREAD

**Issue by markwallsgrove** [npm/node-which#25]
Versions 1.2.2 & 1.2.3 have suddenly disappeared from NPM. Please could you upload them again? Weirdly the `versions` element within the XML doesn't include either version, but the `time` element does include them https://registry.npmjs.org/which/.

![image](https://cloud.githubusercontent.com/assets/6328824/13948013/aae178ea-f015-11e5-97e8-d084fedeabe1.png)

![image](https://cloud.githubusercontent.com/assets/6328824/13948008/a21cec6c-f015-11e5-8a39-6a3ba7b99b04.png)

**Comment by elgertam** [comment]
I'm seeing this issue as well.

**Comment by isaacs** [comment]
1. Those versions were unpublished on purpose.  They were fundamentally broken, and the bug was corrected in 1.2.4. (see: 257dff20447aca250eb5aba6909507b133ae02c1 and 2d5dbe5)
2. That's JSON, not XML.
3. The `time` field includes all versions that have ever been published, even if they are subsequently unpublished.
4. No, I cannot upload versions 1.2.2 and 1.2.3 again, because once a version number is used, it can never be re-used again.  This is by design.

Use 1.2.4 instead.

**Comment by nicolasguenther** [comment]
You should not unpublish versions because of bugs. Thats why versioning exists. You are accidentally breaking dependency trees in dependant packages.

**Comment by isaacs** [comment]
Anyone using the package at version 1.2.2 or 1.2.3 was already 100% broken.

What package can't be installed?  I'll send them a PR to update their dep.
